# Global Args
ARG WORKDIR_APP=/workspace/app

#Stage 1 - Install dependencies and build the app
FROM debian:latest AS build-env

ARG DEBIAN_FRONTEND=noninteractive

ARG SERVICE_NAME
ARG WORKDIR_APP
ARG PROJECT_PPATH=${SERVICE_NAME}/src/main/dart
WORKDIR ${WORKDIR_APP}

# For certificate validation pass
RUN apt-get update -qq && apt-get install -qq -y --no-install-recommends \
    apt-transport-https \
    gnupg2 \
    wget \
    ca-certificates

RUN apt-get clean

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo 'deb [arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main' | tee /etc/apt/sources.list.d/dart_stable.list

# For Web SDK
RUN echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list

# Install flutter dependencies
RUN apt-get update -qq && apt-get install -qq -y --no-install-recommends \
    libglu1-mesa \
    clang  \
    cmake  \
    ninja-build  \
    pkg-config  \
    libgtk-3-dev  \
    liblzma-dev \
    curl\
    git \
    unzip \
    google-chrome-stable

RUN apt-get clean

# Clone the flutter repo
RUN git clone https://github.com/flutter/flutter.git /usr/local/flutter

# Set flutter path
# RUN /usr/local/flutter/bin/flutter doctor -v
ENV PATH="/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin:${PATH}"
RUN flutter config --no-analytics --enable-web --no-enable-android --no-enable-ios

# Run flutter doctor
RUN flutter doctor -v
# Enable flutter web
RUN flutter channel master
RUN flutter upgrade
RUN flutter pub global activate webdev
# Cache web sdk
RUN flutter precache --web

# Copy files to container and build
COPY ${PROJECT_PPATH}/pubspec.yaml ./pubspec.yaml

# Resolve project dependencies
RUN flutter pub get

COPY ${PROJECT_PPATH}/. .

RUN flutter build web

# Stage 2 - Create the run-time image
FROM nginx:1.23.1-alpine

ARG WORKDIR_APP

COPY ./docker/flutter/nginx_default.conf /etc/nginx/conf.d/default.conf
COPY --from=build-env ${WORKDIR_APP}/build/web /usr/share/nginx/html
