FROM nginx:1.23.1-alpine
ARG SERVICE_NAME
ARG PROJECT_PPATH=${SERVICE_NAME}/src/main/dart
COPY ./docker/flutter/nginx_default.conf /etc/nginx/conf.d/default.conf
COPY ${PROJECT_PPATH}/build/web /usr/share/nginx/html