CREATE SCHEMA IF NOT EXISTS VISITS_SCHEMA;

SET SCHEMA VISITS_SCHEMA;

-- Entities Tables
CREATE TABLE VISITS
(
    ID          IDENTITY NOT NULL,
    VISIT_DATE  DATE,
    DESCRIPTION VARCHAR(100),
    PET_ID      INTEGER,
    CONSTRAINT PK__SPECIALTIES__ID PRIMARY KEY (ID)
);

-- Sequence Tables
CREATE TABLE APP_SEQ_GENERATOR
(
    SEQ_NAME  VARCHAR(100) NOT NULL,
    SEQ_VALUE BIGINT       NOT NULL
);

-- Must have data
INSERT INTO APP_SEQ_GENERATOR
VALUES ('VISIT_SEQ_PK', 1);
