CREATE SCHEMA IF NOT EXISTS VETS_SCHEMA;

SET SCHEMA VETS_SCHEMA;

-- Entities Tables
CREATE TABLE SPECIALTIES
(
    ID         IDENTITY NOT NULL,
    NAME VARCHAR(100),
    CONSTRAINT PK__SPECIALTIES__ID PRIMARY KEY (ID)
);

CREATE TABLE VETS
(
    ID         IDENTITY NOT NULL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME  VARCHAR(100),
    CONSTRAINT PK__VETS__ID PRIMARY KEY (ID)
);

-- Join Tables
CREATE TABLE VET_SPECIALTIES
(
    VET_ID    BIGINT NOT NULL,
    CONSTRAINT FK__VETS_SPECIALTIES__VETS FOREIGN KEY (VET_ID) REFERENCES VETS (ID) ON DELETE CASCADE,
    SPECIALTY_ID BIGINT NOT NULL,
    CONSTRAINT FK__VETS_SPECIALTIES__SPECIALTIES FOREIGN KEY (SPECIALTY_ID) REFERENCES VETS (ID) ON DELETE CASCADE,
    CONSTRAINT PK__VETS_SPECIALTIES__VET_ID__SPECIALTY_ID PRIMARY KEY (VET_ID, SPECIALTY_ID)
);

-- Sequence Tables
CREATE TABLE APP_SEQ_GENERATOR
(
    SEQ_NAME  VARCHAR(100) NOT NULL,
    SEQ_VALUE BIGINT       NOT NULL
);

-- Must have data
INSERT INTO APP_SEQ_GENERATOR
VALUES ('VET_SEQ_PK', 1),
       ('SPECIALTY_SEQ_PK', 1);