CREATE SCHEMA IF NOT EXISTS CUSTOMERS_SCHEMA;

SET SCHEMA CUSTOMERS_SCHEMA;

-- Entities Tables
CREATE TABLE OWNER
(
    ID         IDENTITY NOT NULL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME  VARCHAR(100),
    ADDRESS    VARCHAR(100),
    CITY       VARCHAR(100),
    TELEPHONE  VARCHAR(100),
    CONSTRAINT PK__OWNER__ID PRIMARY KEY (ID)
);

CREATE TABLE PET_TYPE
(
    ID   IDENTITY NOT NULL,
    CONSTRAINT PK__PET_TYPE__ID PRIMARY KEY (ID),
    NAME VARCHAR(100)
);

CREATE TABLE PET
(
    ID         IDENTITY NOT NULL,
    CONSTRAINT PK__PET__ID PRIMARY KEY (ID),
    NAME       VARCHAR(100),
    BIRTH_DATE DATE,
    TYPE_ID    BIGINT  NOT NULL,
    CONSTRAINT FK__PET__PET_TYPE FOREIGN KEY (TYPE_ID) REFERENCES PET_TYPE (ID),
    OWNER_ID   BIGINT  NOT NULL,
    CONSTRAINT FK__PET__OWNER FOREIGN KEY (OWNER_ID) REFERENCES OWNER (ID)

);

-- Sequence Tables
CREATE TABLE APP_SEQ_GENERATOR
(
    SEQ_NAME  VARCHAR(100) NOT NULL,
    SEQ_VALUE BIGINT       NOT NULL
);

-- Must have data
INSERT INTO APP_SEQ_GENERATOR
VALUES ('OWNER_SEQ_PK', 1),
       ('PET_TYPE_SEQ_PK', 1),
       ('PET_SEQ_PK', 1);
