# https://github.com/grafana/loki/blob/main/clients/cmd/promtail/promtail-local-config.yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki-server:3100/loki/api/v1/push

scrape_configs:
  - job_name: promtail-server
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/services/**/*log